# Generated by Django 2.2.24 on 2021-11-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
