# Generated by Django 2.2.24 on 2021-11-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211119_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='ref',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
