# Generated by Django 3.2.9 on 2021-11-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_transaction_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='address',
            field=models.CharField(default='4567 7820 3223 0098', max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ref',
            field=models.CharField(default='refrence token', max_length=30),
        ),
    ]
