# Generated by Django 3.2.9 on 2021-11-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20211120_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='phone',
            field=models.IntegerField(default='0701234803'),
        ),
    ]
