# Generated by Django 3.2.9 on 2021-11-21 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20211120_1549'),
        ('myapp', '0011_alter_transaction_phone'),
    ]

    operations = [
    ]
