# Generated by Django 3.2.9 on 2021-11-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20211121_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ref',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
