# Generated by Django 3.2.9 on 2021-11-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_transaction_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='address',
            field=models.TextField(max_length=120, null=True),
        ),
    ]
