# Generated by Django 3.2.9 on 2021-11-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_transaction_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ref',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
